export * as pomoc from './pomoc'
export * as alko from './alko'
export * as urodziny from './urodziny'
// export * as admin from './admin'
export * as event from './event'
export * as zakład from './zaklad'
